export extern "crm current" []
export extern "crm default" []
export extern "crm install" []
export extern "crm list" []
export extern "crm publish" []
export extern "crm remove" []
export extern "crm save" []
export extern "crm test" []
export extern "crm update" []
export extern "crm use" []
export extern "crm version" []
export extern "crm check-update" []
export extern "crm best git" []
export extern "crm best sparse" []
export extern "crm best git-download" []
export extern "crm best sparse-download" []
