export use ./rustfmt-completions.nu *
export use ./rustup-completions.nu *
export use ./pnpm-completions.nu *
export use ./bacon.nu
export use ./gix.nu *
export use ./hx-completions.nu *
export use ./crm.nu *
export use ./cargo.nu *
export use ./kondo.nu *
export use ./cargo-ftag.nu *
export use ./cargo-nextest.nu *
export use ./cargo-update.nu *
export use ./cargo-tarpaulin.nu *
export use ./git.nu *
export use ./hyprland.nu *
export use ./paru.nu *
export use ./systemctl.nu *
export use ./nmcli.nu *
export use ./evcxr.nu *
export use ./file.nu *
export use ./gh.nu *
export use ./mcfly.nu *
export use ./ripgrep.nu *
